name: flutter_app
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
  assets:
  - assets/images/image_17.png
  - assets/images/image_16.png
  - assets/images/image_7.png
  - assets/images/unsplash_0_vsk_29_dkqo_5.jpeg
  - assets/vectors/vector_211_x2.svg
  - assets/vectors/vector_158_x2.svg
  - assets/vectors/battery_3_x2.svg
  - assets/vectors/vector_29_x2.svg
  - assets/vectors/cellular_connection_1_x2.svg
  - assets/vectors/vector_319_x2.svg
  - assets/vectors/vector_274_x2.svg
  - assets/vectors/rectangle_87_x2.svg
  - assets/vectors/vector_108_x2.svg
  - assets/vectors/vector_62_x2.svg
  - assets/vectors/vector_8_x2.svg
  - assets/vectors/wifi_18_x2.svg
  - assets/vectors/vector_202_x2.svg
  - assets/images/image_14.png
  - assets/images/image_11.png
  - assets/images/image_12.png
  - assets/images/image_13.png
  - assets/images/image_15.png
  - assets/images/ellipse_1.jpeg
  - assets/vectors/vector_269_x2.svg
  - assets/vectors/battery_18_x2.svg
  - assets/vectors/vector_117_x2.svg
  - assets/vectors/vector_194_x2.svg
  - assets/vectors/vector_102_x2.svg
  - assets/vectors/vector_243_x2.svg
  - assets/vectors/vector_185_x2.svg
  - assets/vectors/group_3_x2.svg
  - assets/vectors/cellular_connection_x2.svg
  - assets/vectors/wifi_19_x2.svg
  - assets/vectors/vector_89_x2.svg
  - assets/vectors/vector_3_x2.svg
  - assets/vectors/ellipse_12_x2.svg
  - assets/vectors/vector_58_x2.svg
  - assets/vectors/vector_199_x2.svg
  - assets/vectors/union_3_x2.svg
  - assets/vectors/vector_78_x2.svg
  - assets/vectors/cellular_connection_20_x2.svg
  - assets/vectors/union_7_x2.svg
  - assets/vectors/battery_11_x2.svg
  - assets/vectors/vector_248_x2.svg
  - assets/vectors/vector_55_x2.svg
  - assets/vectors/vector_215_x2.svg
  - assets/vectors/component_11_x2.svg
  - assets/vectors/vector_86_x2.svg
  - assets/vectors/vector_88_x2.svg
  - assets/vectors/wifi_9_x2.svg
  - assets/vectors/vector_45_x2.svg
  - assets/vectors/vector_150_x2.svg
  - assets/images/image_7.png
  - assets/vectors/battery_16_x2.svg
  - assets/vectors/wifi_3_x2.svg
  - assets/vectors/cellular_connection_7_x2.svg
  - assets/images/image_12.png
  - assets/images/unsplash_gcdjllzo_klo.jpeg
  - assets/images/image_14.png
  - assets/images/image_17.png
  - assets/images/image_15.png
  - assets/images/image_11.png
  - assets/images/unsplash_3_q_3_ts_j_01_nc.jpeg
  - assets/images/image_13.png
  - assets/images/ellipse_4.jpeg
  - assets/images/unsplash_oyye_4_gi_5_zq.jpeg
  - assets/images/image_16.png
  - assets/images/unsplashx_pjyl_0_l_5_ii_8.jpeg
  - assets/vectors/cellular_connection_5_x2.svg
  - assets/vectors/wifi_17_x2.svg
  - assets/vectors/vector_265_x2.svg
  - assets/vectors/vector_270_x2.svg
  - assets/vectors/vector_282_x2.svg
  - assets/vectors/vector_251_x2.svg
  - assets/vectors/vector_204_x2.svg
  - assets/vectors/battery_5_x2.svg
  - assets/vectors/vector_43_x2.svg
  - assets/vectors/vector_218_x2.svg
  - assets/vectors/cellular_connection_14_x2.svg
  - assets/vectors/iconcircle_x2.svg
  - assets/vectors/battery_12_x2.svg
  - assets/vectors/wifi_5_x2.svg
  - assets/vectors/vector_98_x2.svg
  - assets/vectors/vector_95_x2.svg
  - assets/vectors/union_1_x2.svg
  - assets/images/ellipse_1.jpeg
  - assets/images/image_17.png
  - assets/images/ellipse_4.jpeg
  - assets/images/image_16.png
  - assets/vectors/vector_289_x2.svg
  - assets/vectors/vector_224_x2.svg
  - assets/vectors/ellipse_6_x2.svg
  - assets/vectors/cellular_connection_22_x2.svg
  - assets/vectors/vector_241_x2.svg
  - assets/vectors/vector_210_x2.svg
  - assets/vectors/ellipse_5_x2.svg
  - assets/vectors/battery_13_x2.svg
  - assets/vectors/wifi_12_x2.svg
  - assets/images/ellipse_1.jpeg
  - assets/images/ellipse_4.jpeg
  - assets/images/ellipse_2.jpeg
  - assets/images/ellipse_3.jpeg
  - assets/vectors/vector_328_x2.svg
  - assets/vectors/battery_20_x2.svg
  - assets/vectors/vector_330_x2.svg
  - assets/vectors/vector_208_x2.svg
  - assets/vectors/wifi_22_x2.svg
  - assets/vectors/union_10_x2.svg
  - assets/vectors/cellular_connection_18_x2.svg
  - assets/images/unsplash_oyye_4_gi_5_zq.jpeg
  - assets/images/image_16.png
  - assets/images/unsplashx_pjyl_0_l_5_ii_8.jpeg
  - assets/images/unsplash_3_q_3_ts_j_01_nc.jpeg
  - assets/images/ellipse_4.jpeg
  - assets/images/image_15.png
  - assets/images/image_11.png
  - assets/images/image_13.png
  - assets/images/image_12.png
  - assets/images/image_17.png
  - assets/images/image_14.png
  - assets/images/unsplash_gcdjllzo_klo.jpeg
  - assets/vectors/wifi_6_x2.svg
  - assets/vectors/vector_66_x2.svg
  - assets/vectors/cellular_connection_9_x2.svg
  - assets/vectors/vector_63_x2.svg
  - assets/vectors/vector_275_x2.svg
  - assets/vectors/vector_57_x2.svg
  - assets/vectors/battery_7_x2.svg
  - assets/vectors/vector_25_x2.svg
  - assets/vectors/vector_21_x2.svg
  - assets/images/unsplash_pdds_9_xs_wyo_m_1.png
  - assets/images/unsplashy_tbmycc_zqrs_4.png
  - assets/images/unsplashy_tbmycc_zqrs_1.jpeg
  - assets/images/unsplash_0_vsk_29_dkqo_3.png
  - assets/images/image_7.png
  - assets/images/image_17.png
  - assets/images/unsplash_0_vsk_29_dkqo_6.jpeg
  - assets/images/unsplash_9_u_18_fiowwbw.png
  - assets/images/unsplashy_tbmycc_zqrs_7.jpeg
  - assets/images/image_16.png
  - assets/images/unsplash_0_vsk_29_dkqo_5.jpeg
  - assets/images/unsplash_pdds_9_xs_wyo_m.png
  - assets/images/unsplash_0_vsk_29_dkqo_1.png
  - assets/images/unsplash_9_u_18_fiowwbw_1.png
  - assets/images/unsplashy_tbmycc_zqrs_6.png
  - assets/vectors/vector_180_x2.svg
  - assets/vectors/vector_301_x2.svg
  - assets/vectors/vector_283_x2.svg
  - assets/vectors/vector_90_x2.svg
  - assets/vectors/vector_329_x2.svg
  - assets/vectors/vector_292_x2.svg
  - assets/vectors/vector_104_x2.svg
  - assets/vectors/vector_147_x2.svg
  - assets/vectors/vector_106_x2.svg
  - assets/vectors/vector_4_x2.svg
  - assets/vectors/vector_161_x2.svg
  - assets/vectors/vector_216_x2.svg
  - assets/vectors/cellular_connection_10_x2.svg
  - assets/vectors/vector_149_x2.svg
  - assets/vectors/vector_315_x2.svg
  - assets/vectors/vector_227_x2.svg
  - assets/vectors/vector_278_x2.svg
  - assets/vectors/vector_41_x2.svg
  - assets/vectors/wifi_4_x2.svg
  - assets/vectors/vector_222_x2.svg
  - assets/vectors/vector_230_x2.svg
  - assets/vectors/component_21_x2.svg
  - assets/vectors/vector_186_x2.svg
  - assets/vectors/vector_15_x2.svg
  - assets/vectors/vector_191_x2.svg
  - assets/vectors/vector_156_x2.svg
  - assets/vectors/vector_72_x2.svg
  - assets/vectors/vector_201_x2.svg
  - assets/vectors/vector_118_x2.svg
  - assets/vectors/vector_164_x2.svg
  - assets/vectors/vector_155_x2.svg
  - assets/vectors/vector_131_x2.svg
  - assets/vectors/vector_163_x2.svg
  - assets/vectors/vector_238_x2.svg
  - assets/vectors/vector_165_x2.svg
  - assets/vectors/vector_266_x2.svg
  - assets/vectors/vector_321_x2.svg
  - assets/vectors/vector_313_x2.svg
  - assets/vectors/vector_44_x2.svg
  - assets/vectors/vector_273_x2.svg
  - assets/vectors/vector_19_x2.svg
  - assets/vectors/vector_16_x2.svg
  - assets/vectors/vector_232_x2.svg
  - assets/vectors/vector_141_x2.svg
  - assets/vectors/vector_260_x2.svg
  - assets/vectors/battery_10_x2.svg
  - assets/vectors/vector_80_x2.svg
  - assets/vectors/vector_235_x2.svg
  - assets/vectors/vector_228_x2.svg
  - assets/vectors/vector_252_x2.svg
  - assets/vectors/vector_239_x2.svg
  - assets/vectors/vector_255_x2.svg
  - assets/vectors/vector_254_x2.svg
  - assets/vectors/vector_298_x2.svg
  - assets/vectors/vector_67_x2.svg
  - assets/vectors/vector_119_x2.svg
  - assets/vectors/vector_113_x2.svg
  - assets/vectors/vector_85_x2.svg
  - assets/vectors/vector_184_x2.svg
  - assets/vectors/vector_100_x2.svg
  - assets/vectors/vector_179_x2.svg
  - assets/vectors/vector_91_x2.svg
  - assets/vectors/vector_145_x2.svg
  - assets/vectors/vector_280_x2.svg
  - assets/vectors/vector_300_x2.svg
  - assets/vectors/vector_139_x2.svg
  - assets/vectors/vector_68_x2.svg
  - assets/vectors/vector_229_x2.svg
  - assets/vectors/vector_168_x2.svg
  - assets/vectors/vector_121_x2.svg
  - assets/vectors/vector_77_x2.svg
  - assets/images/image_7.png
  - assets/vectors/wifi_8_x2.svg
  - assets/vectors/battery_8_x2.svg
  - assets/vectors/cellular_connection_12_x2.svg
  - assets/vectors/cellular_connection_21_x2.svg
  - assets/vectors/battery_19_x2.svg
  - assets/vectors/combined_shape_2_x2.svg
  - assets/vectors/backspace_x2.svg
  - assets/vectors/wifi_13_x2.svg
  - assets/vectors/emoji_1_x2.svg
  - assets/vectors/union_4_x2.svg
  - assets/vectors/mic_x2.svg
  - assets/vectors/combined_shape_x2.svg
  - assets/vectors/wifi_2_x2.svg
  - assets/vectors/emoji_x2.svg
  - assets/vectors/cellular_connection_19_x2.svg
  - assets/vectors/backspace_2_x2.svg
  - assets/vectors/mic_2_x2.svg
  - assets/vectors/union_5_x2.svg
  - assets/vectors/battery_1_x2.svg
  - assets/vectors/iconshare_android_x2.svg
  - assets/images/ellipse.jpeg
  - assets/images/ellipse_2.jpeg
  - assets/vectors/union_6_x2.svg
  - assets/vectors/wifi_20_x2.svg
  - assets/vectors/vector_237_x2.svg
  - assets/vectors/vector_123_x2.svg
  - assets/vectors/cellular_connection_3_x2.svg
  - assets/vectors/battery_x2.svg
  - assets/vectors/vector_219_x2.svg
  - assets/vectors/ellipse_7_x2.svg
  - assets/images/image_17.png
  - assets/images/unsplash_0_vsk_29_dkqo_3.png
  - assets/images/unsplash_pdds_9_xs_wyo_m_1.png
  - assets/images/image_16.png
  - assets/images/unsplashy_tbmycc_zqrs_6.png
  - assets/images/unsplash_0_vsk_29_dkqo_1.png
  - assets/images/unsplash_9_u_18_fiowwbw.png
  - assets/images/unsplash_pdds_9_xs_wyo_m.png
  - assets/images/unsplashy_tbmycc_zqrs_5.jpeg
  - assets/images/image_7.png
  - assets/images/unsplashy_tbmycc_zqrs_4.png
  - assets/images/unsplash_0_vsk_29_dkqo_7.jpeg
  - assets/images/unsplash_9_u_18_fiowwbw_1.png
  - assets/images/unsplash_0_vsk_29_dkqo_4.jpeg
  - assets/images/unsplashy_tbmycc_zqrs.jpeg
  - assets/vectors/vector_160_x2.svg
  - assets/vectors/vector_244_x2.svg
  - assets/vectors/vector_316_x2.svg
  - assets/vectors/vector_221_x2.svg
  - assets/vectors/vector_126_x2.svg
  - assets/vectors/vector_12_x2.svg
  - assets/vectors/battery_15_x2.svg
  - assets/vectors/vector_190_x2.svg
  - assets/vectors/vector_54_x2.svg
  - assets/vectors/vector_256_x2.svg
  - assets/vectors/vector_135_x2.svg
  - assets/vectors/vector_264_x2.svg
  - assets/vectors/vector_206_x2.svg
  - assets/vectors/vector_294_x2.svg
  - assets/vectors/vector_296_x2.svg
  - assets/vectors/vector_13_x2.svg
  - assets/vectors/vector_285_x2.svg
  - assets/vectors/vector_209_x2.svg
  - assets/vectors/vector_188_x2.svg
  - assets/vectors/wifi_11_x2.svg
  - assets/vectors/vector_332_x2.svg
  - assets/vectors/vector_308_x2.svg
  - assets/vectors/vector_286_x2.svg
  - assets/vectors/vector_38_x2.svg
  - assets/vectors/vector_120_x2.svg
  - assets/vectors/vector_307_x2.svg
  - assets/vectors/vector_207_x2.svg
  - assets/vectors/vector_196_x2.svg
  - assets/vectors/vector_279_x2.svg
  - assets/vectors/vector_173_x2.svg
  - assets/vectors/vector_303_x2.svg
  - assets/vectors/vector_200_x2.svg
  - assets/vectors/vector_69_x2.svg
  - assets/vectors/vector_47_x2.svg
  - assets/vectors/vector_124_x2.svg
  - assets/vectors/vector_34_x2.svg
  - assets/vectors/vector_295_x2.svg
  - assets/vectors/vector_52_x2.svg
  - assets/vectors/vector_111_x2.svg
  - assets/vectors/vector_250_x2.svg
  - assets/vectors/vector_183_x2.svg
  - assets/vectors/vector_157_x2.svg
  - assets/vectors/vector_28_x2.svg
  - assets/vectors/vector_23_x2.svg
  - assets/vectors/vector_304_x2.svg
  - assets/vectors/vector_162_x2.svg
  - assets/vectors/vector_174_x2.svg
  - assets/vectors/vector_213_x2.svg
  - assets/vectors/vector_51_x2.svg
  - assets/vectors/vector_148_x2.svg
  - assets/vectors/vector_253_x2.svg
  - assets/vectors/vector_212_x2.svg
  - assets/vectors/vector_1_x2.svg
  - assets/vectors/vector_134_x2.svg
  - assets/vectors/vector_322_x2.svg
  - assets/vectors/vector_159_x2.svg
  - assets/vectors/vector_261_x2.svg
  - assets/vectors/vector_56_x2.svg
  - assets/vectors/cellular_connection_16_x2.svg
  - assets/vectors/vector_276_x2.svg
  - assets/vectors/vector_198_x2.svg
  - assets/vectors/vector_262_x2.svg
  - assets/vectors/vector_192_x2.svg
  - assets/vectors/vector_26_x2.svg
  - assets/vectors/vector_71_x2.svg
  - assets/vectors/vector_146_x2.svg
  - assets/vectors/vector_36_x2.svg
  - assets/vectors/vector_326_x2.svg
  - assets/vectors/vector_182_x2.svg
  - assets/images/image_17.png
  - assets/images/image_18.png
  - assets/images/share_streamline_ultimate_png.png
  - assets/images/unsplash_0_vsk_29_dkqo_5.jpeg
  - assets/images/image_19.png
  - assets/vectors/cellular_connection_15_x2.svg
  - assets/vectors/vector_96_x2.svg
  - assets/vectors/battery_22_x2.svg
  - assets/vectors/wifi_x2.svg
  - assets/vectors/vector_18_x2.svg
  - assets/vectors/vector_142_x2.svg
  - assets/vectors/vector_263_x2.svg
  - assets/vectors/group_1_x2.svg
  - assets/vectors/vector_267_x2.svg
  - assets/vectors/vector_302_x2.svg
  - assets/vectors/vector_312_x2.svg
  - assets/images/unsplash_0_vsk_29_dkqo_5.jpeg
  - assets/images/ellipse.jpeg
  - assets/images/ellipse_1.jpeg
  - assets/vectors/chevron_1_x2.svg
  - assets/vectors/vector_99_x2.svg
  - assets/vectors/union_2_x2.svg
  - assets/vectors/vector_203_x2.svg
  - assets/vectors/vector_311_x2.svg
  - assets/vectors/wifi_16_x2.svg
  - assets/vectors/cellular_connection_17_x2.svg
  - assets/vectors/battery_21_x2.svg
  - assets/vectors/vector_325_x2.svg
  - assets/vectors/vector_195_x2.svg
  - assets/vectors/vector_154_x2.svg
  - assets/vectors/vector_197_x2.svg
  - assets/vectors/vector_92_x2.svg
  - assets/vectors/union_x2.svg
  - assets/vectors/wifi_7_x2.svg
  - assets/vectors/cellular_connection_6_x2.svg
  - assets/vectors/battery_17_x2.svg
  - assets/vectors/vector_83_x2.svg
  - assets/vectors/ellipse_1_x2.svg
  - assets/vectors/combined_shape_1_x2.svg
  - assets/vectors/emoji_2_x2.svg
  - assets/vectors/wifi_10_x2.svg
  - assets/vectors/battery_14_x2.svg
  - assets/vectors/union_11_x2.svg
  - assets/vectors/backspace_1_x2.svg
  - assets/vectors/mic_1_x2.svg
  - assets/vectors/cellular_connection_2_x2.svg
  - assets/vectors/vector_39_x2.svg
  - assets/vectors/component_2_x2.svg
  - assets/vectors/vector_137_x2.svg
  - assets/images/ellipse.jpeg
  - assets/vectors/vector_2_x2.svg
  - assets/vectors/group_2_x2.svg
  - assets/vectors/vector_42_x2.svg
  - assets/vectors/battery_4_x2.svg
  - assets/vectors/cellular_connection_13_x2.svg
  - assets/vectors/vector_6_x2.svg
  - assets/vectors/vector_169_x2.svg
  - assets/vectors/vector_48_x2.svg
  - assets/vectors/vector_125_x2.svg
  - assets/vectors/vector_60_x2.svg
  - assets/vectors/vector_167_x2.svg
  - assets/vectors/union_8_x2.svg
  - assets/vectors/cellular_connection_11_x2.svg
  - assets/vectors/battery_6_x2.svg
  - assets/vectors/vector_277_x2.svg
  - assets/vectors/wifi_14_x2.svg
  - assets/vectors/ellipse_11_x2.svg
  - assets/vectors/vector_178_x2.svg
  - assets/vectors/vector_37_x2.svg
  - assets/vectors/vector_87_x2.svg
  - assets/vectors/vector_84_x2.svg
  - assets/vectors/vector_14_x2.svg
  - assets/vectors/vector_220_x2.svg
  - assets/vectors/vector_105_x2.svg
  - assets/vectors/component_1_x2.svg
  - assets/vectors/union_12_x2.svg
  - assets/vectors/wifi_15_x2.svg
  - assets/vectors/vector_79_x2.svg
  - assets/vectors/vector_5_x2.svg
  - assets/images/unsplash_0_vsk_29_dkqo_5.jpeg
  - assets/images/ellipse_1.jpeg
  - assets/images/ellipse.jpeg
  - assets/vectors/chevron_x2.svg
  - assets/vectors/battery_9_x2.svg
  - assets/vectors/vector_76_x2.svg
  - assets/vectors/vector_299_x2.svg
  - assets/vectors/vector_133_x2.svg
  - assets/vectors/vector_59_x2.svg
  - assets/vectors/wifi_21_x2.svg
  - assets/vectors/cellular_connection_8_x2.svg
  - assets/vectors/vector_49_x2.svg
  - assets/vectors/union_9_x2.svg
  - assets/images/unsplash_0_vsk_29_dkqo_1.png
  - assets/images/unsplash_9_u_18_fiowwbw.png
  - assets/images/unsplash_9_u_18_fiowwbw_1.png
  - assets/images/unsplash_pdds_9_xs_wyo_m.png
  - assets/images/image_16.png
  - assets/images/unsplash_0_vsk_29_dkqo_3.png
  - assets/images/unsplash_0_vsk_29_dkqo_2.jpeg
  - assets/images/image_17.png
  - assets/images/unsplashy_tbmycc_zqrs_3.jpeg
  - assets/images/unsplashy_tbmycc_zqrs_2.jpeg
  - assets/images/unsplash_0_vsk_29_dkqo.jpeg
  - assets/images/unsplashy_tbmycc_zqrs_4.png
  - assets/images/unsplashy_tbmycc_zqrs_6.png
  - assets/images/image_7.png
  - assets/images/unsplash_pdds_9_xs_wyo_m_1.png
  - assets/vectors/vector_281_x2.svg
  - assets/vectors/vector_7_x2.svg
  - assets/vectors/vector_73_x2.svg
  - assets/vectors/vector_74_x2.svg
  - assets/vectors/vector_246_x2.svg
  - assets/vectors/vector_128_x2.svg
  - assets/vectors/component_22_x2.svg
  - assets/vectors/vector_323_x2.svg
  - assets/vectors/wifi_1_x2.svg
  - assets/vectors/vector_81_x2.svg
  - assets/vectors/vector_11_x2.svg
  - assets/vectors/vector_249_x2.svg
  - assets/vectors/vector_324_x2.svg
  - assets/vectors/vector_259_x2.svg
  - assets/vectors/vector_17_x2.svg
  - assets/vectors/vector_132_x2.svg
  - assets/vectors/cellular_connection_4_x2.svg
  - assets/vectors/vector_293_x2.svg
  - assets/vectors/vector_242_x2.svg
  - assets/vectors/vector_214_x2.svg
  - assets/vectors/vector_205_x2.svg
  - assets/vectors/vector_130_x2.svg
  - assets/vectors/vector_70_x2.svg
  - assets/vectors/vector_189_x2.svg
  - assets/vectors/vector_233_x2.svg
  - assets/vectors/battery_2_x2.svg
  - assets/vectors/vector_75_x2.svg
  - assets/vectors/vector_136_x2.svg
  - assets/vectors/vector_257_x2.svg
  - assets/vectors/vector_284_x2.svg
  - assets/vectors/vector_27_x2.svg
  - assets/vectors/vector_97_x2.svg
  - assets/vectors/vector_101_x2.svg
  - assets/vectors/vector_175_x2.svg
  - assets/vectors/vector_225_x2.svg
  - assets/vectors/vector_226_x2.svg
  - assets/vectors/vector_50_x2.svg
  - assets/vectors/vector_331_x2.svg
  - assets/vectors/vector_127_x2.svg
  - assets/vectors/vector_53_x2.svg
  - assets/vectors/vector_236_x2.svg
  - assets/vectors/vector_152_x2.svg
  - assets/vectors/vector_109_x2.svg
  - assets/vectors/vector_110_x2.svg
  - assets/vectors/vector_172_x2.svg
  - assets/vectors/vector_320_x2.svg
  - assets/vectors/vector_310_x2.svg
  - assets/vectors/vector_309_x2.svg
  - assets/vectors/vector_20_x2.svg
  - assets/vectors/vector_40_x2.svg
  - assets/vectors/vector_107_x2.svg
  - assets/vectors/vector_217_x2.svg
  - assets/vectors/vector_170_x2.svg
  - assets/vectors/vector_333_x2.svg
  - assets/vectors/vector_176_x2.svg
  - assets/vectors/vector_65_x2.svg
  - assets/vectors/vector_10_x2.svg
  - assets/vectors/vector_171_x2.svg
  - assets/vectors/vector_193_x2.svg
  - assets/vectors/vector_93_x2.svg
  - assets/vectors/vector_129_x2.svg
  - assets/vectors/vector_290_x2.svg
  - assets/vectors/vector_181_x2.svg
  - assets/vectors/vector_116_x2.svg
  - assets/vectors/vector_94_x2.svg
  - assets/vectors/vector_138_x2.svg
  - assets/vectors/vector_35_x2.svg
  - assets/vectors/vector_115_x2.svg

